spring:
  mvc: 
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:oracle:thin:@192.168.10.224:1521:MCSJT
    username: MCS_JT
    password: MCS_JT
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update